# Generated by Django 5.0.6 on 2024-07-15 14:24

import company.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=100,
                        validators=[company.validators.phone_number_validator],
                    ),
                ),
                ("message", models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name="Sponser",
            new_name="Sponsor",
        ),
    ]
